name: Cypress Testing

on:
  pull_request:
    branches: master

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.0-slim-chrome99-ff97
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Cypress
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - run: pwd
      - run: ls -a
      - name: Save node_modules folder
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          if-no-files-found: error
          path: node_modules

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.0-slim-chrome99-ff97
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the node_modules folders
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules
      - run: pwd
      - run: ls -a
      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
          spec: cypress/tests/ui/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
